FROM alpine:latest as HUGO
ENV HUGO_VERSION=0.80.0
# install hugo
# change workdir for npm
WORKDIR /site

EXPOSE 1313

ENV UID=1000 GID=1000 THEME="techdoc" REPO_NAME=BrianRagazzi/hugosite REPO_BRANCH=lab REPO_TOKEN=token

COPY ./run.sh /run.sh
ADD https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz /tmp/


ENV HUGO_ID=hugo_${HUGO_VERSION}
RUN tar -xf /tmp/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -C /tmp/ \
    && mkdir -p /usr/local/sbin \
    && mv /tmp/hugo /usr/local/sbin/hugo \
    && rm -rf /tmp/${HUGO_ID}_linux_amd64 \
    && rm -rf /tmp/LICENSE.md \
    && rm -rf /tmp/README.md \
    && chmod +x /usr/local/sbin/hugo \
    && apk add --update git npm libc6-compat libstdc++ \
    && apk upgrade \
    && apk add --no-cache ca-certificates \
    && chmod 0777 /run.sh

VOLUME /site
VOLUME /output

WORKDIR /
CMD ["/run.sh"]

EXPOSE 1313
