FROM harbor.ragazzilab.com/tanzu-sql/tanzu-mysql-instance:1.0.0

ADD files/* /etc/mysqlrouter/
# USER root
# RUN apt-get update && apt-get upgrade libnettle6 liblz4-1 libhogweed4 -y
# \
#  && apt-get upgrade -y \
#  && rm -rf /var/lib/apt/lists/*
